version: '3.8'

services:
  api:
    image: rocketpay:${APP_VERSION:-latest}
    ports:
      - "4000:4000"
    depends_on:
      - postgres
  postgres:
    image: postgres:${POSTGRES_VERSION:-13-alpine}
    env_file: ./docker/postgres/.env.production
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    command: -p ${POSTGRES_PORT:-5432}
volumes:
  pgdata:
networks:
  default:
    name: rocketpay