version: '3.8'

services:
  api:
    image: rocketpay:${APP_VERSION:-latest}
    container_name: api
    env_file: .env.dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        ELIXIR_VERSION: ${ELIXIR_VERSION:-1.11-alpine}
        USER: ${USER:-elixir}
        GID: ${GID:-1000}
        UID: ${UID:-1000}
    healthcheck:
      test: ["CMD", "curl", "http://localhost:${PORT:-80}/api"]
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - .:${HOME}/app
      - ${HOME}/app/deps
      - ${HOME}/app/_build
  grafana:
    container_name: grafana
    env_file: ./docker/grafana/.env.dev
  prometheus:
    container_name: prometheus
  postgres_exporter:
    container_name: postgres_exporter
    env_file: ./docker/postgres_exporter/.env.dev
  postgres:
    container_name: postgres
    env_file: ./docker/postgres/.env.dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 5s
      retries: 5