version: '3.8'

services:
  api:
    image: ${ECR_REGISTRY:?required}/rocketpay:${APP_VERSION:-latest}
    environment:
      SIGNING_SALT: ${SIGNING_SALT}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DB_URL: ${DB_URL}
      DB_PORT: ${DB_PORT}
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      AUTH_USERNAME: ${AUTH_USERNAME}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
      AUTH_SECRET: ${AUTH_SECRET}
    ports:
      - target: 4000
        x-aws-protocol: http
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 1Gb

networks:
  default:
    external: true
    name: "sg-050e85439302b4f4c"

x-aws-loadbalancer: arn:aws:elasticloadbalancing:us-east-1:688285194038:loadbalancer/net/rocketpay/b9e45ffad6192caf

x-aws-cloudformation:
  Resources:
    Cluster:
      Properties:
        ClusterName: rocketpay
    ApiService:
      Properties:
        ServiceName: rocketpay-ApiService
