version: '3.8'

services:
  api:
    image: ${ECR_REGISTRY:?required}/rocketpay:${APP_VERSION:-latest}
    environment:
      SIGNING_SALT: ${SIGNING_SALT}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DB_URL: ${DB_URL}
      DB_PORT: ${DB_PORT}
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      AUTH_USERNAME: ${AUTH_USERNAME}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
      AUTH_SECRET: ${AUTH_SECRET}
    ports:
      - target: 4000
        x-aws-protocol: http
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 1Gb

networks:
  default:
    external: true
    name: "sg-050e85439302b4f4c"

x-aws-loadbalancer: arn:aws:elasticloadbalancing:us-east-1:688285194038:loadbalancer/app/rocketpay/c7db50ddd3350f2e

x-aws-cloudformation:
  Resources:
    Cluster:
      Properties:
        ClusterName: rocketpay
    ApiService:
      Properties:
        ServiceName: rocketpay-ApiService
    Api4000TargetGroup:
      Properties:
        Name: rocketpay
        HealthCheckPath: /api/index.html
        Matcher:
          HttpCode: 200-399
    Api80Listener:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        LoadBalancerArn: arn:aws:elasticloadbalancing:us-east-1:688285194038:loadbalancer/app/rocketpay/c7db50ddd3350f2e
        Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: redirect
            RedirectConfig:
              Host: '#{host}'
              Path: '/#{path}'
              Port: 443
              Protocol: HTTPS
              Query: '#{query}'
              StatusCode: HTTP_301
    Api443Listener:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        LoadBalancerArn: arn:aws:elasticloadbalancing:us-east-1:688285194038:loadbalancer/app/rocketpay/c7db50ddd3350f2e
        Protocol: HTTPS
        Port: 443
        SslPolicy: ELBSecurityPolicy-2016-08
        Certificates:
          - CertificateArn: arn:aws:acm:us-east-1:688285194038:certificate/a46c3c8f-9f69-44dd-a3ef-1915880ffef6
        DefaultActions:
          - Type: forward
            ForwardConfig:
              TargetGroups:
                - TargetGroupArn:
                    Ref: Api4000TargetGroup