{
 "title": "General",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(erlang_vm_process_count, instance)"
    }
   },
   {
    "name": "interval",
    "query": "10s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=\"$node\"}[$interval])) without (kind) * 100"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "µs",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\"}[$interval]))/sum(rate(http_request_duration_microseconds_count{instance=\"$node\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{instance=\"$node\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Atoms",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "erlang_vm_atom_count{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "erlang_vm_process_count{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Ports",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "erlang_vm_port_count{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", status_class=\"informational\"}[$interval]))/sum(rate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"informational\"}[$interval]))",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", status_class=\"success\"}[$interval]))/sum(rate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"success\"}[$interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", status_class=\"redirection\"}[$interval]))/sum(rate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"redirection\"}[$interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", status_class=\"client-error\"}[$interval]))/sum(rate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"client-error\"}[$interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", status_class=\"server-error\"}[$interval]))/sum(rate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"server-error\"}[$interval]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", status_class=\"unknown\"}[$interval]))/sum(rate(http_request_duration_microseconds_count{instance=\"$node\", reason=\"unknown\"}[$interval]))",
     "legendFormat": "unknown"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"informational\"}[$interval]))",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"success\"}[$interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"redirection\"}[$interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"client-error\"}[$interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"server-error\"}[$interval]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"unknown\"}[$interval]))",
     "legendFormat": "unknown"
    },
    {
     "expr": "sum by (reason)(rate(http_requests_failed_total{instance=\"$node\", reason=\"request_closed\"}[$interval]))",
     "legendFormat": "closed"
    },
    {
     "expr": "sum by (reason)(rate(http_requests_failed_total{instance=\"$node\", reason=\"timeout\"}[$interval]))",
     "legendFormat": "timeout"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(erlang_vm_statistics_context_switches{instance=\"$node\"}[$interval])",
     "legendFormat": "Context Switches"
    },
    {
     "expr": "rate(erlang_vm_statistics_reductions_total{instance=\"$node\"}[$interval])",
     "legendFormat": "Reductions"
    }
   ]
  },
  {
   "title": "Native Threads & CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "process_threads_total{instance=\"$node\"}",
     "legendFormat": "Threads"
    },
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=\"$node\"}[$interval])) without (kind) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "VM GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(erlang_vm_statistics_garbage_collection_number_of_gcs{instance=\"$node\"}[$interval])",
     "legendFormat": "Number of GCs"
    },
    {
     "expr": "rate(erlang_vm_statistics_garbage_collection_bytes_reclaimed{instance=\"$node\"}[$interval])",
     "legendFormat": "Bytes Reclaimed"
    }
   ]
  },
  {
   "title": "VM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_memory_bytes_total{instance=\"$node\", kind=\"processes\"}",
     "legendFormat": "Processes Memory"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"atom\"}",
     "legendFormat": "Atoms"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"binary\"}",
     "legendFormat": "Binary"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"code\"}",
     "legendFormat": "Code"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"ets\"}",
     "legendFormat": "ETS"
    }
   ]
  },
  {
   "title": "OS Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$node\"}",
     "legendFormat": "Vertual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"$node\"}",
     "legendFormat": "Resident Memory"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_process_count{instance=\"$node\"}",
     "legendFormat": "Processes"
    },
    {
     "expr": "erlang_vm_statistics_run_queues_length_total{instance=\"$node\"}",
     "legendFormat": "Run Queues Length"
    }
   ]
  },
  {
   "title": "File Descriptors & Ports",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$node\"}",
     "legendFormat": "Open FDs"
    },
    {
     "expr": "process_max_fds{instance=\"$node\"}",
     "legendFormat": "Max FDs"
    },
    {
     "expr": "erlang_vm_port_limit{instance=\"$node\"}",
     "legendFormat": "Max Ports"
    },
    {
     "expr": "erlang_vm_port_count{instance=\"$node\"}",
     "legendFormat": "Ports"
    }
   ]
  },
  {
   "title": "VM IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(erlang_vm_statistics_bytes_output_total{instance=\"$node\"}[$interval])",
     "legendFormat": "Output Bytes"
    },
    {
     "expr": "rate(erlang_vm_statistics_bytes_received_total{instance=\"$node\"}[$interval])",
     "legendFormat": "Received Bytes"
    }
   ]
  },
  {
   "title": "Ecto Query Duration, $interval average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(ecto_query_duration_microseconds_sum{instance=\"$node\", result=\"ok\"}[$interval]) / rate(ecto_query_duration_microseconds_count{instance=\"$node\", result=\"ok\"}[$interval])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(ecto_query_duration_microseconds_sum{instance=\"$node\", result=\"error\"}[$interval]) / rate(ecto_query_duration_microseconds_count{instance=\"$node\", result=\"error\"}[$interval])",
     "legendFormat": "error"
    }
   ]
  }
 ]
}