{
 "title": "Requests",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(erlang_vm_process_count, instance)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Deposit ~> Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"PUT\", path=~\".*/deposit$\", status_class=\"informational\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/deposit$\", status_class=\"informational\"}[$interval]))",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"PUT\", path=~\".*/deposit$\", status_class=\"success\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/deposit$\", status_class=\"success\"}[$interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"PUT\", path=~\".*/deposit$\", status_class=\"redirection\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/deposit$\", status_class=\"redirection\"}[$interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"PUT\", path=~\".*/deposit$\", status_class=\"client-error\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/deposit$\", status_class=\"client-error\"}[$interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"PUT\", path=~\".*/deposit$\", status_class=\"server-error\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/deposit$\", status_class=\"server-error\"}[$interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Deposit ~> Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/deposit$\", status_class=\"informational\"}[$interval]))",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/deposit$\", status_class=\"success\"}[$interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/deposit$\", status_class=\"redirection\"}[$interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/deposit$\", status_class=\"client-error\"}[$interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/deposit$\", status_class=\"server-error\"}[$interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Withdraw ~> Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"PUT\", path=~\".*/withdraw$\", status_class=\"informational\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/withdraw$\", status_class=\"informational\"}[$interval]))",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"PUT\", path=~\".*/withdraw$\", status_class=\"success\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/withdraw$\", status_class=\"success\"}[$interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"PUT\", path=~\".*/withdraw$\", status_class=\"redirection\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/withdraw$\", status_class=\"redirection\"}[$interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"PUT\", path=~\".*/withdraw$\", status_class=\"client-error\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/withdraw$\", status_class=\"client-error\"}[$interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"PUT\", path=~\".*/withdraw$\", status_class=\"server-error\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/withdraw$\", status_class=\"server-error\"}[$interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Withdraw ~> Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/withdraw$\", status_class=\"informational\"}[$interval]))",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/withdraw$\", status_class=\"success\"}[$interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/withdraw$\", status_class=\"redirection\"}[$interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/withdraw$\", status_class=\"client-error\"}[$interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/withdraw$\", status_class=\"server-error\"}[$interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Transaction ~> Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"PUT\", path=~\".*/transaction$\", status_class=\"informational\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/transaction$\", status_class=\"informational\"}[$interval]))",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"PUT\", path=~\".*/transaction$\", status_class=\"success\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/transaction$\", status_class=\"success\"}[$interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"PUT\", path=~\".*/transaction$\", status_class=\"redirection\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/transaction$\", status_class=\"redirection\"}[$interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"PUT\", path=~\".*/transaction$\", status_class=\"client-error\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/transaction$\", status_class=\"client-error\"}[$interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"PUT\", path=~\".*/transaction$\", status_class=\"server-error\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/transaction$\", status_class=\"server-error\"}[$interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Transaction ~> Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/transaction$\", status_class=\"informational\"}[$interval]))",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/transaction$\", status_class=\"success\"}[$interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/transaction$\", status_class=\"redirection\"}[$interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/transaction$\", status_class=\"client-error\"}[$interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"PUT\", path=~\".*/transaction$\", status_class=\"server-error\"}[$interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Login ~> Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"POST\", path=~\".*/login$\", status_class=\"informational\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"POST\", path=~\".*/login$\", status_class=\"informational\"}[$interval]))",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"POST\", path=~\".*/login$\", status_class=\"success\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"POST\", path=~\".*/login$\", status_class=\"success\"}[$interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"POST\", path=~\".*/login$\", status_class=\"redirection\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"POST\", path=~\".*/login$\", status_class=\"redirection\"}[$interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"POST\", path=~\".*/login$\", status_class=\"client-error\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"POST\", path=~\".*/login$\", status_class=\"client-error\"}[$interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"POST\", path=~\".*/login$\", status_class=\"server-error\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"POST\", path=~\".*/login$\", status_class=\"server-error\"}[$interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Login ~> Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"POST\", path=~\".*/login$\", status_class=\"informational\"}[$interval]))",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"POST\", path=~\".*/login$\", status_class=\"success\"}[$interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"POST\", path=~\".*/login$\", status_class=\"redirection\"}[$interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"POST\", path=~\".*/login$\", status_class=\"client-error\"}[$interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"POST\", path=~\".*/login$\", status_class=\"server-error\"}[$interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Register ~> Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"POST\", path=~\".*/users$\", status_class=\"informational\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"POST\", path=~\".*/users$\", status_class=\"informational\"}[$interval]))",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"POST\", path=~\".*/users$\", status_class=\"success\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"POST\", path=~\".*/users$\", status_class=\"success\"}[$interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"POST\", path=~\".*/users$\", status_class=\"redirection\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"POST\", path=~\".*/users$\", status_class=\"redirection\"}[$interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"POST\", path=~\".*/users$\", status_class=\"client-error\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"POST\", path=~\".*/users$\", status_class=\"client-error\"}[$interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\", method=\"POST\", path=~\".*/users$\", status_class=\"server-error\"}[$interval])) / sum(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"POST\", path=~\".*/users$\", status_class=\"server-error\"}[$interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Register ~> Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"POST\", path=~\".*/users$\", status_class=\"informational\"}[$interval]))",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"POST\", path=~\".*/users$\", status_class=\"success\"}[$interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"POST\", path=~\".*/users$\", status_class=\"redirection\"}[$interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"POST\", path=~\".*/users$\", status_class=\"client-error\"}[$interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum by (status_class)(rate(http_request_duration_microseconds_count{instance=\"$node\", method=\"POST\", path=~\".*/users$\", status_class=\"server-error\"}[$interval]))",
     "legendFormat": "5xx"
    }
   ]
  }
 ]
}